package helper;

public enum FailType {

    UPDATE_RESERVATION_FOR_FOREIGN_MEMBER,
    SAVE_RESERVATION_FOR_FOREIGN_MEMBER,
    DELETE_FOREIGN_RESERVATION,
    UNKNOWN_RESERVATION_STATE,
    DOUBLE_RESERVED_VEHICLE,
    NUMBER_PLATE_USED_TWICE,
    UNKNOWN_RESERVATION_ID,
    UNKNOWN_ACCOUNT_TYPE,
    PASSWORD_INADEQUATE,
    PATCHING_START_DATE,
    EMPLOYEE_ID_IN_USE,
    UNKNOWN_VEHICLE_ID,
    LICENSE_ID_IN_USE,
    PATCHING_END_DATE,
    UNKNOWN_FARE_TYPE,
    PATCHING_CURRENCY,
    PATCHING_VEHICLE,
    PATCHING_DRIVER,
    INVALID_PERIOD,
    EMAIL_IN_USE,
    PATCH_PRICE,
    WRONG_PRICE,
    FIELD_BLANK,
    FIELD_NULL,
    NONE

}
