@baseUrl = http://localhost:8080/vehicle

GET {{baseUrl}}

###
GET {{baseUrl}}/1


###
POST {{baseUrl}}
Content-Type: application/json

{
  "brand": "Volvo",
  "model": "S40",
  "numberPlate": "sdsdsd<>",
  "latitude": 53.079296,
  "longitude": 8.801694,
  "constructionYear": 2009,
  "configuration": {
    "vehicleCategory": {
      "id": "F"
    },
    "vehicleType": {
      "id": "R"
    },
    "vehicleTransmission": {
      "id": "N"
    },
    "vehicleFuel": {
      "id": "Q"
    },
    "equipment": {
      "hasAc": true,
      "hasNavigation": false,
      "hasCruiseControl": true,
      "hasDrivingAssistant": false
    }
  }
}


###
PATCH {{baseUrl}}/1


###
DELETE {{baseUrl}}/5
